parameters:
# nothing to declare
services:
  Mubiridziri\Geocenter\Service\Transport:
    arguments: [ '', '@http_client' ]
  Mubiridziri\Geocenter\Module\Geodecoder:
    arguments: [ '', '@Mubiridziri\Geocenter\Service\Transport', '@serializer' ]

