parameters:
# nothing to declare
services:
  Mubiridziri\Geocenter\Service\Transport:
    arguments: [ '', '@http_client' ]
  Mubiridziri\Geocenter\Module\Geodecoder:
    arguments: [ '', '@Mubiridziri\Geocenter\Service\Transport', '@serializer' ]
  Mubiridziri\Geocenter\Module\ReverseGeodecode:
    arguments: [ '', '@Mubiridziri\Geocenter\Service\Transport', '@serializer' ]
  Mubiridziri\Geocenter\Service\GeocenterManager:
    arguments: [ '@Mubiridziri\Geocenter\Module\Geodecoder', '@Mubiridziri\Geocenter\Module\ReverseGeodecode' ]

